# Use "\n" to make a new line
# Use "ยง" to give colors to texts

# Changing the title of KygekJoinUI
title: "KygekJoinUI"

# Changing the content of KygekJoinUI
content: "Change in config.yml"

# Changing the button on KygekJoinUI
buttons:
- "bruh test"
- "test 2"
...
